### ISSUE TITLE
Add Contributor Guidelines

### ISSUE THREAD

**Issue by prjailani** [davorg/planetskeptic#7]
Hi sir/madam,
    Can I add contributor guidelines. If yes please assign me. Thanks.

**Comment by prjailani** [comment]
> Do you think the lack of contributor guidelines is stopping people from contributing to the project? What would your guidelines include?

@davorg maybe beginner needs this. I include how to do it from git pull to git push and create pull request for that. Also I include thanks for the contributors at the end and mention the contributors GitHub profiles. We need to thank those amazing people, right?

**Comment by prjailani** [comment]
> Maybe. I'm not convinced.
> 
> Please tell me what draws you particularly to this project.

If you don't want then I'll close this issue. I searched for Hacktoberfest and recently merged and then find your repo. Anyways Thanks.

**Comment by davorg** [comment]
See, this is the problem. You have no real interest in my project. You're just looking for easy targets to get pull requests. Do you really want a t-shirt that badly?
